name: Build
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-14
    steps:
      - uses: actions/checkout@v4

      - name: Build
        run: |
          brew install make ldid
          git clone --recursive https://github.com/theos/theos.git ~/theos
          export THEOS=~/theos
          make clean package FINALPACKAGE=1

      - uses: actions/upload-artifact@v4
        with:
          name: Deb
          path: packages/*.deb
